import UIProvider from '@/components/UIProvider/Provider'
import './globals.css'
import { Bricolage_Grotesque } from 'next/font/google'

const bricolage_grot = Bricolage_Grotesque({ subsets: ['latin'] })

export const metadata = {
  title: 'Limma Hair Oil',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={bricolage_grot.className}>
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  )
}
